// Suggestions for "country" fields. Any value can still be typed; the list keeps spelling consistent.
export const COUNTRY_SUGGESTIONS = [
  "Poland",
  "Germany",
  "Czechia",
  "Slovakia",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Serbia",
  "Slovenia",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Netherlands",
  "Belgium",
  "Luxembourg",
  "France",
  "Spain",
  "Portugal",
  "Italy",
  "Malta",
  "Greece",
  "Cyprus",
  "Austria",
  "Denmark",
  "Sweden",
  "Finland",
  "Norway",
  "Iceland",
  "Ireland",
  "Switzerland",
  "Albania",
  "Bosnia and Herzegovina",
  "Montenegro",
  "North Macedonia",
  "Moldova",
  "Ukraine",
  "United Kingdom",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Canada",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
]
